2021-07-01 18:03:12,082 logger.py[line:50] INFO Open url: https://www.nhtest.com/en/customer/account/login
2021-07-01 18:03:12,199 logger.py[line:50] INFO Maximize the current window.
2021-07-01 18:03:12,389 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-07-01 18:03:12,389 logger.py[line:50] INFO Set implicitly wait 10 seconds.
2021-07-01 18:03:15,398 logger.py[line:50] INFO Had find the element //*[@id="email"] successful 
2021-07-01 18:03:15,615 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-07-01 18:03:15,616 logger.py[line:50] INFO Had type ' 2770488802@qq.com ' in inputBox
2021-07-01 18:03:18,623 logger.py[line:50] INFO Had find the element //*[@id="password"] successful 
2021-07-01 18:03:18,832 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-07-01 18:03:18,833 logger.py[line:50] INFO Had type ' 123456 ' in inputBox
2021-07-01 18:03:21,980 logger.py[line:50] INFO Had take screenshot and save to folder : \screenshots
2021-07-01 18:03:21,988 logger.py[line:50] INFO Had find the element //*[@id="saveButton"] successful 
2021-07-01 18:03:26,931 logger.py[line:50] INFO The element xpath=>//*[@id="saveButton"] was clicked.
2021-07-01 18:03:29,931 logger.py[line:50] INFO Now, Close and quit the browser.
2021-07-01 18:03:34,089 connectionpool.py[line:662] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D23D02CA90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8816d874e2db9f51c7c87e48d90fcac8/url
2021-07-01 18:03:36,093 connectionpool.py[line:662] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D23D02C668>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8816d874e2db9f51c7c87e48d90fcac8/url
2021-07-01 18:03:38,096 connectionpool.py[line:662] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D23D02C898>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8816d874e2db9f51c7c87e48d90fcac8/url
2021-07-01 18:03:40,265 logger.py[line:50] INFO Now, Close and quit the browser.
2021-07-01 18:03:42,270 connectionpool.py[line:662] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D23DBD65F8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8816d874e2db9f51c7c87e48d90fcac8
2021-07-01 18:03:44,273 connectionpool.py[line:662] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D23DBD6E80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8816d874e2db9f51c7c87e48d90fcac8
2021-07-01 18:03:46,275 connectionpool.py[line:662] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D23DBD6780>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8816d874e2db9f51c7c87e48d90fcac8
2021-07-01 18:03:50,284 connectionpool.py[line:662] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D23DBD6EB8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8816d874e2db9f51c7c87e48d90fcac8/url
2021-07-01 18:03:52,287 connectionpool.py[line:662] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D23DBD6048>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8816d874e2db9f51c7c87e48d90fcac8/url
2021-07-01 18:03:54,292 connectionpool.py[line:662] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D23DBD64E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8816d874e2db9f51c7c87e48d90fcac8/url
2021-07-01 18:03:56,416 logger.py[line:50] INFO Now, Close and quit the browser.
2021-07-01 18:03:58,418 connectionpool.py[line:662] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D23DB3F668>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8816d874e2db9f51c7c87e48d90fcac8
2021-07-01 18:04:00,421 connectionpool.py[line:662] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D23DB3F630>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8816d874e2db9f51c7c87e48d90fcac8
2021-07-01 18:04:02,423 connectionpool.py[line:662] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D23DB3F7B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8816d874e2db9f51c7c87e48d90fcac8
