2021-02-02 16:25:09,789 logger.py[line:50] INFO You had select Chrome browser.
2021-02-02 16:25:09,790 logger.py[line:50] INFO The test server url is: https://www.nhtest.com/
2021-02-02 16:25:13,011 logger.py[line:50] INFO Starting Chrome browser.
2021-02-02 16:25:13,523 logger.py[line:50] INFO Open url: https://www.nhtest.com/
2021-02-02 16:25:15,638 logger.py[line:50] INFO Maximize the current window.
2021-02-02 16:25:15,639 logger.py[line:50] INFO Set implicitly wait 10 seconds.
2021-02-02 16:25:19,830 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028A9F034EB8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/d7a2eead7e645f603b32531a075f7acb
2021-02-02 16:25:21,835 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028A9F101668>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/d7a2eead7e645f603b32531a075f7acb
2021-02-02 16:25:23,838 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028A9F101860>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/d7a2eead7e645f603b32531a075f7acb
2021-02-02 16:25:27,852 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028A9F11B198>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/d7a2eead7e645f603b32531a075f7acb
2021-02-02 16:25:29,855 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028A9F11B208>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/d7a2eead7e645f603b32531a075f7acb
2021-02-02 16:25:31,857 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028A9F11B4E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/d7a2eead7e645f603b32531a075f7acb
