2021-02-02 16:27:07,194 logger.py[line:50] INFO You had select Chrome browser.
2021-02-02 16:27:07,194 logger.py[line:50] INFO The test server url is: https://www.nhtest.com/
2021-02-02 16:27:10,416 logger.py[line:50] INFO Starting Chrome browser.
2021-02-02 16:27:10,585 logger.py[line:50] INFO Open url: https://www.nhtest.com/
2021-02-02 16:27:12,701 logger.py[line:50] INFO Maximize the current window.
2021-02-02 16:27:12,702 logger.py[line:50] INFO Set implicitly wait 10 seconds.
2021-02-02 16:27:16,866 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026CD8833C88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/63ac26a45a6bc837c6009778cb24c3c1
2021-02-02 16:27:18,869 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026CD88FE4E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/63ac26a45a6bc837c6009778cb24c3c1
2021-02-02 16:27:20,872 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026CD88FE6D8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/63ac26a45a6bc837c6009778cb24c3c1
2021-02-02 16:27:24,888 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026CD891D208>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/63ac26a45a6bc837c6009778cb24c3c1
2021-02-02 16:27:26,891 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026CD891D2B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/63ac26a45a6bc837c6009778cb24c3c1
2021-02-02 16:27:28,896 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026CD891D470>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/63ac26a45a6bc837c6009778cb24c3c1
