2021-02-02 16:28:20,727 logger.py[line:50] INFO You had select Chrome browser.
2021-02-02 16:28:20,727 logger.py[line:50] INFO The test server url is: https://www.nhtest.com/
2021-02-02 16:28:23,883 logger.py[line:50] INFO Starting Chrome browser.
2021-02-02 16:28:24,115 logger.py[line:50] INFO Open url: https://www.nhtest.com/
2021-02-02 16:28:26,238 logger.py[line:50] INFO Maximize the current window.
2021-02-02 16:28:26,239 logger.py[line:50] INFO Set implicitly wait 10 seconds.
2021-02-02 16:28:30,414 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002388B653C50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/ca4473398e249bc9933d9536502ece78
2021-02-02 16:28:32,417 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002388B71E550>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/ca4473398e249bc9933d9536502ece78
2021-02-02 16:28:34,421 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002388B71E748>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/ca4473398e249bc9933d9536502ece78
2021-02-02 16:28:38,434 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002388B73D240>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/ca4473398e249bc9933d9536502ece78
2021-02-02 16:28:40,436 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002388B73D358>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/ca4473398e249bc9933d9536502ece78
2021-02-02 16:28:42,438 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002388B73D5C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/ca4473398e249bc9933d9536502ece78
